### ISSUE TITLE
Getting around issue with misaligned traffic lights

### ISSUE THREAD

**Issue by insomnia-creator** [aureness/firefoxCSS-Safari#5]
How would one align the traffic lights correctly? Example
![CleanShot 2024-10-25 at 18 26 59@2x](https://github.com/user-attachments/assets/fcef0168-e762-419c-96a0-27a6568042ca)

They're slightly misaligned below the actual lining. This is because of the about.config -> 
![CleanShot 2024-10-25 at 18 27 33@2x](https://github.com/user-attachments/assets/94a85a27-4d7d-4004-867c-f625873fe071)

If we reset it to -1.0(default value) the issue if fixed albeit the UI is now extremely large for my preference.
![CleanShot 2024-10-25 at 18 27 46@2x](https://github.com/user-attachments/assets/df763f83-f3ce-4720-a025-9c2719140ec6)

 Is this any way we can get around this? Thank you. I tried to see if there is a variable giving this value to me in the css but to no avail. It would be easy to put this value into a slow growing function and keep it aligned.

**Comment by aureness** [comment]
I have replicated your problem

Here quick workaround:
You may add these lines, where 16px was eyeballed for `layout.css.devPixelsPerPx: 1.9`
```
.titlebar-buttonbox {
  height: 16px;
}
```

<img width="433" alt="Screenshot 2024-10-26 at 01 42 39" src="https://github.com/user-attachments/assets/bb48c61c-882f-466f-8134-33c4f2667249">


I don't know how we can get this scaling factor in CSS tho

**Comment by insomnia-creator** [comment]
I did manually change it earlier, but it's not a permanent solution is it?

**Comment by aureness** [comment]
We can actually test what devPixelsPerPx is and set custom styles for reasonable amount of them up to 2
Like this: 
```
@media ( -webkit-min-device-pixel-ratio: 1.2) {
  .titlebar-buttonbox {
    min-height: 25px;
  }
}

@media ( -webkit-min-device-pixel-ratio: 1.3) {
  .titlebar-buttonbox {
    min-height: 21px;
  }
}

@media ( -webkit-min-device-pixel-ratio: 1.4) {
  .titlebar-buttonbox {
    min-height: 17px;
  }
}

@media ( -webkit-min-device-pixel-ratio: 1.6) {
  .titlebar-buttonbox {
    min-height: 17px;
  }
}

@media ( -webkit-min-device-pixel-ratio: 1.9) {
  .titlebar-buttonbox {
    min-height: 16px;
  }
}

@media ( -webkit-min-device-pixel-ratio: 2) {
  .titlebar-buttonbox {
    min-height: initial;
  }
}
```
2 is default macOS retina scale and buttons stop to overflow this box ugly.
Also one can tweak other values in these blocks.

I just have tried this and it works.

Or one can try define a variable in these blocks like
```
@media ( -webkit-min-device-pixel-ratio: 1) {
  :root {
    --device-pixel-ratio: 1;
  }
}
...
@media ( -webkit-min-device-pixel-ratio: 2) {
  :root {
    --device-pixel-ratio: 2;
  }
}
```
And add a multiplier to necessary values as `calc(val(--device-pixel-ratio) * <default-value>)`

**Comment by aureness** [comment]
```
@media (max--moz-device-pixel-ratio: 1.9)
```
probably would be better.  moz- prefix feels better in mozilla's browser (but -webkit works too 🙂)

**Comment by insomnia-creator** [comment]
Is it a good idea to try and have these scales incorporated into the repo?

**Comment by aureness** [comment]
I don't know, I don't think it's necessary. Any user can tweak theme as they want for their specific configuration.
Maybe when I'll buy another monitor with different dpi I'll change something, but it's kinda OK now

**Comment by insomnia-creator** [comment]
Closing this is a good idea then.
